name: NextNative
description: App Description
ignoreFiles: .git .next node_modules
modules:
  - name: NativeTest
    language: nodejs14.x
    web: nextjs
    description: Module description
    functions:
      - name: entry
        entry: entry.js
        description: the entry point for the function